# Generated by Django 5.2.17 on 2026-08-06 07:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_name", models.TextField(blank=True)),
                ("name", models.TextField()),
                ("normalized_name", models.TextField(db_index=True)),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("nonprofit", "Nonprofit"),
                            ("public_body", "Public body"),
                            ("agency", "Agency"),
                            ("recruiter", "Recruiter"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                ("industry_key", models.CharField(blank=True, max_length=100)),
                ("headquarters_country", models.CharField(blank=True, max_length=2)),
                ("headquarters_city", models.TextField(blank=True)),
                (
                    "employee_range",
                    models.CharField(
                        choices=[
                            ("1_10", "1-10"),
                            ("11_50", "11-50"),
                            ("51_200", "51-200"),
                            ("201_1000", "201-1,000"),
                            ("1001_plus", "1,001+"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("strategic_fit_manual", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("provisional", "Provisional"),
                            ("archived", "Archived"),
                            ("merge_review", "Merge review"),
                        ],
                        default="provisional",
                        max_length=16,
                    ),
                ),
                ("row_version", models.PositiveBigIntegerField(default=1)),
            ],
            options={
                "ordering": ("name", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("strategic_fit_manual__isnull", True),
                            ("strategic_fit_manual__lte", 100),
                            _connector="OR",
                        ),
                        name="companies_strategic_fit_lte_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["active", "provisional", "archived", "merge_review"])
                        ),
                        name="companies_status_known",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias", models.TextField()),
                ("normalized_alias", models.TextField()),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("source_confirmed", "Source confirmed"),
                            ("human_verified", "Human verified"),
                            ("disputed", "Disputed"),
                        ],
                        default="unverified",
                        max_length=24,
                    ),
                ),
                ("verification_source_url", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliases",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ("alias",),
                "indexes": [
                    models.Index(fields=["normalized_alias"], name="companies_alias_normalized")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "normalized_alias"),
                        name="companies_alias_company_normalized_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hostname_ascii", models.TextField()),
                ("hostname_unicode", models.TextField(blank=True)),
                ("registrable_domain", models.TextField()),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("source_confirmed", "Source confirmed"),
                            ("human_verified", "Human verified"),
                            ("disputed", "Disputed"),
                        ],
                        default="unverified",
                        max_length=24,
                    ),
                ),
                ("verification_source_url", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="domains",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_primary", "hostname_ascii"),
                "indexes": [models.Index(fields=["hostname_ascii"], name="companies_domain_host")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "hostname_ascii"),
                        name="companies_domain_company_host_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("company",),
                        name="companies_one_primary_domain",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyMergeReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("match_method", models.CharField(max_length=64)),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("evidence_source_ids", models.JSONField(blank=True, default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("confirmed_same", "Confirmed same"),
                            ("confirmed_distinct", "Confirmed distinct"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=24,
                    ),
                ),
                ("decision_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "decision_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_merge_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "left_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merge_reviews_as_left",
                        to="companies.company",
                    ),
                ),
                (
                    "right_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merge_reviews_as_right",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("left_company", models.F("right_company")), _negated=True
                        ),
                        name="companies_merge_distinct_companies",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                        name="companies_merge_confidence_range",
                    ),
                ],
            },
        ),
    ]
