# Generated by Django 5.2.17 on 2026-08-06 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="companymergereview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "open")),
                fields=("left_company", "right_company"),
                name="companies_one_open_merge_review_pair",
            ),
        ),
    ]
