# Generated by Django 5.2.17 on 2026-08-12 07:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_companymergereview_companies_one_open_merge_review_pair"),
        ("operations", "0002_audit_event_immutability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfileRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("parser_version", models.CharField(max_length=32)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("source_urls", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("field_count", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("safe_error_message", models.CharField(blank=True, max_length=500)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile_runs",
                        to="companies.company",
                    ),
                ),
                (
                    "pipeline_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_profile_run",
                        to="operations.pipelinerun",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_company_profile_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("request_company_enrichment", "Can request company profile enrichment")
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyProfileSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("homepage", "Homepage"),
                            ("imprint", "Imprint / legal notice"),
                            ("about", "About / company page"),
                            ("other", "Other official page"),
                        ],
                        max_length=16,
                    ),
                ),
                ("requested_url", models.TextField()),
                ("final_url", models.TextField()),
                ("canonical_url_sha256", models.CharField(max_length=64)),
                ("storage_key", models.TextField(unique=True)),
                ("body_sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("content_type", models.CharField(max_length=255)),
                ("encoding", models.CharField(blank=True, max_length=64)),
                ("retrieved_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrichment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="companies.companyprofilerun",
                    ),
                ),
            ],
            options={
                "ordering": ("retrieved_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CompanyFieldObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("legal_name", "Legal name"),
                            ("company_type", "Company type"),
                            ("industry_key", "Industry"),
                            ("headquarters_city", "Headquarters city"),
                            ("headquarters_country", "Headquarters country"),
                            ("employee_range", "Employee range"),
                            ("description", "Description"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value_text", models.TextField()),
                ("normalized_value", models.TextField()),
                ("evidence_excerpt", models.CharField(max_length=1000)),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("extraction_method", models.CharField(max_length=64)),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("applied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrichment_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_observations",
                        to="companies.companyprofilerun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_observations",
                        to="companies.companyprofilesource",
                    ),
                ),
            ],
            options={
                "ordering": ("field_name", "-confidence", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="companyprofilerun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["queued", "running", "complete", "partial", "failed"])
                ),
                name="companies_profile_run_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyprofilesource",
            constraint=models.UniqueConstraint(
                fields=("enrichment_run", "canonical_url_sha256"),
                name="companies_profile_source_run_url_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyprofilesource",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_kind__in", ["homepage", "imprint", "about", "other"])),
                name="companies_profile_source_kind_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyprofilesource",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_bytes__gte", 1)),
                name="companies_profile_source_size_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyfieldobservation",
            constraint=models.UniqueConstraint(
                fields=("enrichment_run", "source", "field_name", "evidence_sha256"),
                name="companies_profile_observation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyfieldobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "field_name__in",
                        [
                            "legal_name",
                            "company_type",
                            "industry_key",
                            "headquarters_city",
                            "headquarters_country",
                            "employee_range",
                            "description",
                        ],
                    )
                ),
                name="companies_profile_field_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyfieldobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="companies_profile_confidence_range",
            ),
        ),
    ]
