# Generated by Django 5.2.17 on 2026-08-06 10:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0002_companymergereview_companies_one_open_merge_review_pair"),
        ("operations", "0002_audit_event_immutability"),
        ("signals", "0003_alter_signalevent_review_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("use_case_family", models.CharField(default="capability_systems", max_length=100)),
                (
                    "qualification_status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("watchlist", "Watchlist"),
                            ("research_eligible", "Research eligible"),
                            ("review_required", "Review required"),
                            ("qualified", "Qualified"),
                            ("rejected", "Rejected"),
                        ],
                        default="candidate",
                        max_length=24,
                    ),
                ),
                (
                    "research_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("queued", "Queued"),
                            ("in_progress", "In progress"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="not_started",
                        max_length=24,
                    ),
                ),
                (
                    "solution_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("review", "Review"),
                            ("complete", "Complete"),
                        ],
                        default="not_started",
                        max_length=24,
                    ),
                ),
                (
                    "outreach_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("review", "Review"),
                            ("complete", "Complete"),
                        ],
                        default="not_started",
                        max_length=24,
                    ),
                ),
                (
                    "relationship_stage",
                    models.CharField(
                        choices=[
                            ("uncontacted", "Uncontacted"),
                            ("contacted", "Contacted"),
                            ("engaged", "Engaged"),
                            ("paused", "Paused"),
                        ],
                        default="uncontacted",
                        max_length=24,
                    ),
                ),
                ("priority_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("score_coverage", models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ("opportunity_mode", models.CharField(blank=True, max_length=24)),
                ("entry_offer_key", models.CharField(blank=True, max_length=100)),
                ("next_action_key", models.CharField(blank=True, max_length=100)),
                ("next_action_at", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="companies.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_for_opportunities",
                        to="signals.signalevent",
                    ),
                ),
            ],
            options={
                "ordering": ("-priority_score", "company__name"),
                "permissions": [("override_opportunity", "Can override opportunity qualification")],
            },
        ),
        migrations.CreateModel(
            name="CompanyAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("superseded", "Superseded"),
                            ("review_required", "Review required"),
                        ],
                        default="completed",
                        max_length=24,
                    ),
                ),
                ("feature_cutoff_at", models.DateTimeField()),
                ("feature_builder_version", models.CharField(max_length=32)),
                ("scoring_policy_version", models.CharField(max_length=32)),
                ("features", models.JSONField(default=dict)),
                ("pattern_keys", models.JSONField(default=list)),
                ("capability_relevance", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "capability_coverage",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                (
                    "commercial_actionability",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "commercial_coverage",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                (
                    "long_term_system_potential",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "long_term_coverage",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                ("strategic_value", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "strategic_coverage",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                ("priority_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "overall_coverage",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                ("selected_signal_ids", models.JSONField(default=list)),
                ("selected_assessment_ids", models.JSONField(default=list)),
                ("missing_components", models.JSONField(default=list)),
                ("input_sha256", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_assessments",
                        to="companies.company",
                    ),
                ),
                (
                    "pipeline_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_assessment",
                        to="operations.pipelinerun",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_assessments",
                        to="opportunities.opportunity",
                    ),
                ),
            ],
            options={
                "ordering": ("-feature_cutoff_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="OpportunitySignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("relationship_type", models.CharField(default="supporting", max_length=32)),
                ("inclusion_reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signal_links",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunity_links",
                        to="signals.signalevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QualificationOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "prior_status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("watchlist", "Watchlist"),
                            ("research_eligible", "Research eligible"),
                            ("review_required", "Review required"),
                            ("qualified", "Qualified"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "selected_status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("watchlist", "Watchlist"),
                            ("research_eligible", "Research eligible"),
                            ("review_required", "Review required"),
                            ("qualified", "Qualified"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunity_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qualification_overrides",
                        to="opportunities.opportunity",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CompanyFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("feature_key", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                ("unit", models.CharField(max_length=32)),
                ("cutoff_at", models.DateTimeField()),
                ("input_record_ids", models.JSONField(default=list)),
                ("input_sha256", models.CharField(max_length=64)),
                ("feature_builder_version", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feature_rows",
                        to="opportunities.companyassessment",
                    ),
                ),
            ],
            options={
                "ordering": ("feature_key",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company_assessment", "feature_key"),
                        name="opportunities_feature_assessment_key_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "pattern_key",
                    models.CharField(
                        choices=[
                            ("isolated_experiment", "Isolated experiment"),
                            ("cross_functional_capability_build", "Cross-functional build"),
                            ("production_capacity_expansion", "Production expansion"),
                            ("internal_platform_build", "Internal platform build"),
                            ("learning_and_enablement_program", "Learning and enablement"),
                            ("local_private_ai_investment", "Local/private AI investment"),
                            ("mature_internal_team", "Mature internal team"),
                            ("weak_or_ambiguous_pattern", "Weak or ambiguous"),
                        ],
                        max_length=64,
                    ),
                ),
                ("feature_cutoff_at", models.DateTimeField()),
                ("rule_version", models.CharField(max_length=32)),
                ("input_signal_ids", models.JSONField(default=list)),
                ("input_sha256", models.CharField(max_length=64)),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("superseded", "Superseded"),
                            ("review_required", "Review required"),
                        ],
                        default="completed",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patterns",
                        to="companies.company",
                    ),
                ),
                (
                    "company_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patterns",
                        to="opportunities.companyassessment",
                    ),
                ),
            ],
            options={
                "ordering": ("pattern_key",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company_assessment", "pattern_key"),
                        name="opportunities_pattern_assessment_key_unique",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("company", "use_case_family"),
                name="opportunities_one_active_company_family",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("priority_score__isnull", True), ("priority_score__lte", 100), _connector="OR"
                ),
                name="opportunities_priority_lte_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunitysignal",
            constraint=models.UniqueConstraint(
                fields=("opportunity", "signal"), name="opportunities_signal_link_unique"
            ),
        ),
    ]
