# Generated by Django 5.2.17 on 2026-08-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyfeature",
            name="value",
            field=models.JSONField(null=True),
        ),
    ]
