# Generated by Django 5.2.17 on 2026-08-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0002_alter_companyfeature_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="research_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("queued", "Queued"),
                    ("in_progress", "In progress"),
                    ("complete", "Complete"),
                    ("partial", "Partial"),
                    ("review_required", "Review required"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                    ("stale", "Stale"),
                ],
                default="not_started",
                max_length=24,
            ),
        ),
    ]
