# Generated by Django 5.2.17 on 2026-08-06 12:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0002_companymergereview_companies_one_open_merge_review_pair"),
        ("operations", "0002_audit_event_immutability"),
        ("opportunities", "0003_alter_opportunity_research_status"),
        ("research", "0002_immutable_research_evidence"),
        ("solutions", "0002_immutable_solution_records"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_id", models.CharField(max_length=10)),
                ("evidence_kind", models.CharField(max_length=32)),
                ("exact_text_ciphertext", models.TextField()),
                ("display_text", models.CharField(max_length=500)),
                ("public_normalized_text", models.CharField(blank=True, max_length=4096)),
                ("encryption_key_id", models.CharField(max_length=64)),
                ("start_offset", models.PositiveIntegerField()),
                ("end_offset", models.PositiveIntegerField()),
                ("exact_text_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("public_id",),
            },
        ),
        migrations.CreateModel(
            name="ContactSourceArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("storage_key", models.CharField(max_length=1000, unique=True)),
                ("requested_url", models.TextField()),
                ("final_url", models.TextField()),
                ("sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("content_type", models.CharField(max_length=255)),
                ("storage_encrypted", models.BooleanField(default=True)),
                ("encryption_key_id", models.CharField(default="", max_length=64)),
                ("retrieved_at", models.DateTimeField()),
                ("status_code", models.PositiveSmallIntegerField()),
                ("redirect_chain", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuyerRoleResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("output_payload", models.JSONField(default=dict)),
                ("input_sha256", models.CharField(max_length=64)),
                ("output_sha256", models.CharField(max_length=64)),
                ("prompt_version", models.CharField(default="2.1.0", max_length=32)),
                ("schema_version", models.CharField(default="2.1", max_length=16)),
                ("generator_method", models.CharField(default="deterministic", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "solution_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buyer_role_result",
                        to="solutions.solutionversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuyerRoleHypothesis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_id", models.CharField(max_length=16)),
                ("role_key", models.CharField(max_length=100)),
                ("owner_type", models.CharField(max_length=48)),
                ("responsibility_match", models.TextField()),
                ("priority", models.PositiveSmallIntegerField()),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("source_ids", models.JSONField(default=list)),
                ("claim_ids", models.JSONField(default=list)),
                ("evidence_ids", models.JSONField(default=list)),
                ("unknowns", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles",
                        to="contacts.buyerroleresult",
                    ),
                ),
            ],
            options={
                "ordering": ("priority",),
            },
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("professional_name", models.CharField(max_length=500)),
                ("normalized_name", models.CharField(db_index=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contact_people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("professional_name",),
            },
        ),
        migrations.CreateModel(
            name="ContactObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role_title", models.CharField(max_length=500)),
                ("department", models.CharField(blank=True, max_length=500)),
                ("observation_origin", models.CharField(max_length=32)),
                ("observed_at", models.DateTimeField()),
                ("freshness_status", models.CharField(default="unknown", max_length=16)),
                ("provenance_note", models.CharField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_observations",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contact_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_observations",
                        to="contacts.contactevidence",
                    ),
                ),
                (
                    "research_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_observations",
                        to="research.researchsource",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_observations",
                        to="contacts.contactperson",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactResearchRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("safe_error_message", models.CharField(blank=True, max_length=500)),
                ("input_sha256", models.CharField(max_length=64)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_research_runs",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "pipeline_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_research_run",
                        to="operations.pipelinerun",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_contact_research_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solution_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_research_runs",
                        to="solutions.solutionversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("request_contact_research", "Can request buyer and contact research")
                ],
            },
        ),
        migrations.AddField(
            model_name="buyerroleresult",
            name="contact_research_run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buyer_role_result",
                to="contacts.contactresearchrun",
            ),
        ),
        migrations.CreateModel(
            name="ContactRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "route_type",
                    models.CharField(
                        choices=[
                            ("role_email", "Role email"),
                            ("individual_business_email", "Business email"),
                            ("contact_form", "Contact form"),
                            ("professional_profile", "Professional profile"),
                            ("phone", "Phone"),
                            ("other_public_route", "Other public route"),
                            ("warm_introduction", "Warm introduction"),
                            ("existing_relationship", "Existing relationship"),
                            ("event_connection", "Event connection"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "route_origin",
                    models.CharField(
                        choices=[
                            ("public_source", "Public source"),
                            ("human_entered", "Human entered"),
                            ("existing_relationship", "Existing relationship"),
                            ("event", "Event"),
                        ],
                        max_length=32,
                    ),
                ),
                ("public_value", models.TextField(blank=True)),
                ("encrypted_value", models.TextField(blank=True)),
                ("value_masked", models.CharField(max_length=500)),
                ("normalized_hmac", models.CharField(max_length=64)),
                ("key_id", models.CharField(max_length=64)),
                ("source_ids", models.JSONField(default=list)),
                ("evidence_ids", models.JSONField(default=list)),
                ("provenance_note", models.CharField(blank=True, max_length=1000)),
                ("retrieved_at", models.DateTimeField()),
                ("last_checked_at", models.DateTimeField()),
                ("observation_status", models.CharField(default="unconfirmed", max_length=32)),
                ("freshness_status", models.CharField(default="unknown", max_length=16)),
                ("deliverability_status", models.CharField(default="unknown", max_length=16)),
                ("outreach_eligibility", models.CharField(default="unreviewed", max_length=40)),
                ("recommendation", models.CharField(default="research_more", max_length=48)),
                ("jurisdiction", models.CharField(blank=True, max_length=2)),
                ("legal_review_status", models.CharField(default="not_reviewed", max_length=32)),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("status", models.CharField(default="active", max_length=16)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_routes",
                        to="contacts.buyerrolehypothesis",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_routes",
                        to="companies.company",
                    ),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_routes",
                        to="contacts.contactperson",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contact_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_routes",
                        to="contacts.contactevidence",
                    ),
                ),
                (
                    "primary_research_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_routes",
                        to="research.researchsource",
                    ),
                ),
            ],
            options={
                "ordering": ("route_type", "created_at"),
                "permissions": [
                    ("add_human_route", "Can add an audited human-origin route"),
                    ("review_contact_route", "Can review contact route eligibility"),
                    ("select_contact_route", "Can select an exact contact route"),
                    ("add_suppression", "Can add a suppression entry"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contact_purpose", models.CharField(max_length=500)),
                ("jurisdiction", models.CharField(max_length=2)),
                ("legal_review_status", models.CharField(max_length=32)),
                ("lawful_basis_note", models.CharField(blank=True, max_length=1000)),
                ("retention_policy", models.CharField(max_length=100)),
                ("route_row_version", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selections",
                        to="contacts.buyerrolehypothesis",
                    ),
                ),
                (
                    "contact_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selections",
                        to="contacts.contactroute",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_selections",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "selected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_selections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solution_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_selections",
                        to="solutions.solutionversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="contactevidence",
            name="artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_items",
                to="contacts.contactsourceartifact",
            ),
        ),
        migrations.CreateModel(
            name="ContactSourceTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("requested_url", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("route_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("safe_error_message", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact_research_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_targets",
                        to="contacts.contactresearchrun",
                    ),
                ),
                (
                    "research_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_source_targets",
                        to="research.researchsource",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.AddField(
            model_name="contactsourceartifact",
            name="target",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifact",
                to="contacts.contactsourcetarget",
            ),
        ),
        migrations.CreateModel(
            name="SuppressionEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("normalized_hmac", models.CharField(blank=True, max_length=64)),
                ("scope_type", models.CharField(max_length=24)),
                ("reason_type", models.CharField(max_length=32)),
                ("reason_note", models.CharField(max_length=1000)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppression_entries",
                        to="companies.company",
                    ),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppression_entries",
                        to="contacts.contactperson",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_suppressions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="buyerrolehypothesis",
            constraint=models.UniqueConstraint(
                fields=("result", "public_id"), name="contacts_role_result_public_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="buyerrolehypothesis",
            constraint=models.UniqueConstraint(
                fields=("result", "role_key"), name="contacts_role_result_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="buyerrolehypothesis",
            constraint=models.UniqueConstraint(
                fields=("result", "priority"), name="contacts_role_result_priority_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="buyerrolehypothesis",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="contacts_role_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactresearchrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["queued", "running", "complete", "partial", "failed"])
                ),
                name="contacts_research_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactroute",
            constraint=models.UniqueConstraint(
                fields=("company", "normalized_hmac"), name="contacts_company_route_hmac_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="contactroute",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="contacts_route_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactroute",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "route_type__in",
                        [
                            "role_email",
                            "individual_business_email",
                            "contact_form",
                            "professional_profile",
                            "phone",
                            "other_public_route",
                            "warm_introduction",
                            "existing_relationship",
                            "event_connection",
                        ],
                    )
                ),
                name="contacts_route_type_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactroute",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "route_origin__in",
                        ["public_source", "human_entered", "existing_relationship", "event"],
                    )
                ),
                name="contacts_route_origin_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactevidence",
            constraint=models.UniqueConstraint(
                fields=("artifact", "public_id"), name="contacts_evidence_artifact_public_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="contactevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_offset__gt", models.F("start_offset"))),
                name="contacts_evidence_offsets_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactsourcetarget",
            constraint=models.UniqueConstraint(
                fields=("contact_research_run", "research_source"),
                name="contacts_target_run_source_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactsourcetarget",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["queued", "running", "complete", "failed"])),
                name="contacts_target_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppressionentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("company__isnull", False),
                    ("contact_person__isnull", False),
                    models.Q(("normalized_hmac", ""), _negated=True),
                    _connector="OR",
                ),
                name="contacts_suppression_has_scope",
            ),
        ),
    ]
