# Generated by Django 5.2.17 on 2026-08-06 08:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0002_companymergereview_companies_one_open_merge_review_pair"),
        ("operations", "0002_audit_event_immutability"),
        ("sources", "0002_immutable_source_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_type", models.CharField(max_length=24)),
                ("external_posting_id", models.CharField(max_length=255)),
                ("canonical_url", models.TextField()),
                ("apply_url", models.TextField(blank=True)),
                ("source_url", models.TextField()),
                ("title", models.CharField(max_length=500)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("team", models.CharField(blank=True, max_length=255)),
                ("employment_type", models.CharField(blank=True, max_length=100)),
                ("language", models.CharField(blank=True, max_length=16)),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed"), ("unknown", "Unknown")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_postings",
                        to="companies.company",
                    ),
                ),
                (
                    "primary_source_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_postings",
                        to="sources.sourceendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_seen_at", "title"),
            },
        ),
        migrations.CreateModel(
            name="JobPostingSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("connector_key", models.CharField(max_length=64)),
                ("connector_version", models.CharField(max_length=32)),
                ("normalizer_version", models.CharField(max_length=32)),
                ("retrieved_at", models.DateTimeField()),
                ("title", models.CharField(max_length=500)),
                ("description_text", models.TextField()),
                ("structured_sections", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                ("locations_payload", models.JSONField(default=list)),
                ("full_hash", models.CharField(max_length=64)),
                ("semantic_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parse_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_posting_snapshots",
                        to="operations.pipelinerun",
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="jobs.jobposting",
                    ),
                ),
                (
                    "source_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_posting_snapshots",
                        to="sources.sourcesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("-retrieved_at",),
            },
        ),
        migrations.AddField(
            model_name="jobposting",
            name="current_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for_postings",
                to="jobs.jobpostingsnapshot",
            ),
        ),
        migrations.CreateModel(
            name="PostingObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("found", "Found"), ("missing", "Missing")],
                        default="found",
                        max_length=16,
                    ),
                ),
                ("provider_identity", models.CharField(max_length=255)),
                ("observed_url", models.TextField()),
                ("observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parse_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posting_observations",
                        to="operations.pipelinerun",
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="jobs.jobposting",
                    ),
                ),
                (
                    "source_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posting_observations",
                        to="sources.sourcesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("-observed_at",),
            },
        ),
        migrations.CreateModel(
            name="ConnectorParseAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("succeeded", "Succeeded"),
                            ("unsupported", "Unsupported"),
                            ("invalid_schema", "Invalid schema"),
                            ("failed", "Failed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("connector_key", models.CharField(blank=True, max_length=64)),
                ("connector_version", models.CharField(blank=True, max_length=32)),
                ("normalizer_version", models.CharField(max_length=32)),
                ("detected_content_type", models.CharField(blank=True, max_length=255)),
                ("posting_count", models.PositiveIntegerField(default=0)),
                ("snapshot_count", models.PositiveIntegerField(default=0)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("elapsed_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("safe_error_message", models.CharField(blank=True, max_length=500)),
                (
                    "pipeline_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connector_parse_attempt",
                        to="operations.pipelinerun",
                    ),
                ),
                (
                    "source_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parse_attempts",
                        to="sources.sourcesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
                "permissions": [("reparse_source_snapshot", "Can reparse a source snapshot")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["started", "succeeded", "unsupported", "invalid_schema", "failed"],
                            )
                        ),
                        name="jobs_parse_status_known",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JobLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ordinal", models.PositiveSmallIntegerField()),
                ("display_text", models.CharField(max_length=500)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("region", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("postal_code", models.CharField(blank=True, max_length=32)),
                ("remote", models.BooleanField(default=False)),
                (
                    "workplace_type",
                    models.CharField(
                        choices=[
                            ("onsite", "On-site"),
                            ("hybrid", "Hybrid"),
                            ("remote", "Remote"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="jobs.jobposting",
                    ),
                ),
            ],
            options={
                "ordering": ("ordinal",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("posting", "ordinal"), name="jobs_location_posting_ordinal_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("workplace_type__in", ["onsite", "hybrid", "remote", "unknown"])
                        ),
                        name="jobs_location_workplace_known",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="jobpostingsnapshot",
            constraint=models.UniqueConstraint(
                fields=("posting", "full_hash"), name="jobs_snapshot_posting_full_hash_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobpostingsnapshot",
            constraint=models.UniqueConstraint(
                fields=("source_snapshot", "posting", "connector_version"),
                name="jobs_snapshot_source_posting_connector_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobposting",
            constraint=models.UniqueConstraint(
                fields=("primary_source_endpoint", "provider_type", "external_posting_id"),
                name="jobs_posting_endpoint_provider_external_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobposting",
            constraint=models.CheckConstraint(
                condition=models.Q(("lifecycle_status__in", ["open", "closed", "unknown"])),
                name="jobs_posting_lifecycle_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobposting",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_seen_at__gte", models.F("first_seen_at"))),
                name="jobs_posting_seen_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="postingobservation",
            constraint=models.UniqueConstraint(
                fields=("posting", "source_snapshot"), name="jobs_observation_posting_source_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="postingobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["found", "missing"])),
                name="jobs_observation_state_known",
            ),
        ),
    ]
