# Generated by Django 5.2.17 on 2026-08-06 08:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_immutable_job_snapshots"),
        ("operations", "0002_audit_event_immutability"),
        ("sources", "0002_immutable_source_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicateRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("duplicate", "Duplicate"),
                            ("translation", "Translation"),
                            ("syndicated", "Syndicated"),
                            ("related", "Related"),
                        ],
                        default="duplicate",
                        max_length=16,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("provider_id", "Provider identity"),
                            ("canonical_url", "Canonical URL"),
                            ("content_hash", "Content hash"),
                            ("rule", "Deterministic rule"),
                            ("semantic_review", "Semantic review"),
                        ],
                        max_length=24,
                    ),
                ),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic"),
                            ("needs_review", "Needs review"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_priority", models.CharField(default="first_party", max_length=16)),
                ("evidence", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PostingChangeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("unchanged", "Unchanged"),
                            ("cosmetic", "Cosmetic"),
                            ("material", "Material"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                        ],
                        max_length=16,
                    ),
                ),
                ("changed_fields", models.JSONField(default=list)),
                ("before_full_hash", models.CharField(blank=True, max_length=64)),
                ("after_full_hash", models.CharField(blank=True, max_length=64)),
                ("policy_version", models.CharField(max_length=32)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-occurred_at", "-created_at"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="postingobservation",
            name="jobs_observation_posting_source_unique",
        ),
        migrations.RemoveConstraint(
            model_name="postingobservation",
            name="jobs_observation_state_known",
        ),
        migrations.AddField(
            model_name="jobposting",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="closure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("consecutive_absence", "Consecutive successful absence"),
                    ("explicit_provider", "Explicit provider closure"),
                    ("valid_through", "Valid-through date"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="normalized_title",
            field=models.CharField(db_index=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="successful_absence_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="postingobservation",
            name="fetch_attempt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posting_observations",
                to="sources.fetchattempt",
            ),
        ),
        migrations.AlterField(
            model_name="postingobservation",
            name="state",
            field=models.CharField(
                choices=[
                    ("found", "Found"),
                    ("missing", "Missing"),
                    ("not_modified", "Not modified"),
                    ("explicit_closed", "Explicitly closed"),
                ],
                default="found",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="postingobservation",
            constraint=models.UniqueConstraint(
                fields=("posting", "fetch_attempt"), name="jobs_observation_posting_fetch_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="postingobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["found", "missing", "not_modified", "explicit_closed"])
                ),
                name="jobs_observation_state_known",
            ),
        ),
        migrations.AddField(
            model_name="duplicaterelationship",
            name="primary_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="duplicate_relationships_as_primary",
                to="jobs.jobposting",
            ),
        ),
        migrations.AddField(
            model_name="duplicaterelationship",
            name="secondary_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="duplicate_relationships_as_secondary",
                to="jobs.jobposting",
            ),
        ),
        migrations.AddField(
            model_name="postingchangeevent",
            name="new_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changes_to",
                to="jobs.jobpostingsnapshot",
            ),
        ),
        migrations.AddField(
            model_name="postingchangeevent",
            name="observation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_event",
                to="jobs.postingobservation",
            ),
        ),
        migrations.AddField(
            model_name="postingchangeevent",
            name="old_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changes_from",
                to="jobs.jobpostingsnapshot",
            ),
        ),
        migrations.AddField(
            model_name="postingchangeevent",
            name="parse_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posting_change_events",
                to="operations.pipelinerun",
            ),
        ),
        migrations.AddField(
            model_name="postingchangeevent",
            name="posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_events",
                to="jobs.jobposting",
            ),
        ),
        migrations.AddField(
            model_name="postingchangeevent",
            name="source_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posting_change_events",
                to="sources.sourcesnapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="duplicaterelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("primary_posting", models.F("secondary_posting")), _negated=True
                ),
                name="jobs_duplicate_distinct_postings",
            ),
        ),
        migrations.AddConstraint(
            model_name="duplicaterelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="jobs_duplicate_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="duplicaterelationship",
            constraint=models.UniqueConstraint(
                fields=("primary_posting", "secondary_posting"),
                name="jobs_duplicate_posting_pair_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="postingchangeevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "change_type__in",
                        ["created", "unchanged", "cosmetic", "material", "closed", "reopened"],
                    )
                ),
                name="jobs_change_type_known",
            ),
        ),
    ]
