# Generated by Django 5.2.17 on 2026-08-06 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_backfill_change_tracking"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="jobpostingsnapshot",
            name="jobs_snapshot_source_posting_connector_unique",
        ),
    ]
