# Generated by Django 5.2.17 on 2026-08-06 10:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_remove_jobpostingsnapshot_jobs_snapshot_source_posting_connector_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceCatalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("builder_version", models.CharField(max_length=32)),
                ("item_count", models.PositiveIntegerField()),
                ("catalog_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_catalogs",
                        to="jobs.jobpostingsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EvidenceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_id", models.CharField(max_length=16)),
                ("field_path", models.CharField(max_length=255)),
                ("exact_text", models.TextField()),
                ("normalized_text", models.TextField()),
                ("start_offset", models.PositiveIntegerField(blank=True, null=True)),
                ("end_offset", models.PositiveIntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("content_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="jobs.evidencecatalog",
                    ),
                ),
            ],
            options={
                "ordering": ("public_id",),
            },
        ),
        migrations.AddConstraint(
            model_name="evidencecatalog",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "builder_version"),
                name="jobs_evidence_catalog_snapshot_builder_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceitem",
            constraint=models.UniqueConstraint(
                fields=("catalog", "public_id"), name="jobs_evidence_item_catalog_public_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("start_offset__isnull", True), ("end_offset__isnull", True)),
                    models.Q(
                        ("start_offset__isnull", False),
                        ("end_offset__isnull", False),
                        ("end_offset__gt", models.F("start_offset")),
                    ),
                    _connector="OR",
                ),
                name="jobs_evidence_item_offset_pair",
            ),
        ),
    ]
