# Generated by Django 5.2.17 on 2026-08-06 11:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField(unique=True)),
                ("source_commit", models.CharField(max_length=64)),
                ("schema_version", models.CharField(default="2.1", max_length=16)),
                ("manifest_sha256", models.CharField(max_length=64, unique=True)),
                ("source_manifest", models.JSONField(default=dict)),
                ("item_counts", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "synced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="synced_knowledge_releases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-version",),
                "permissions": [
                    ("sync_knowledge", "Can sync a validated FTL knowledge release"),
                    ("activate_knowledge", "Can activate an FTL knowledge release"),
                ],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeRegistryState",
            fields=[
                (
                    "registry_key",
                    models.CharField(
                        default="default", max_length=32, primary_key=True, serialize=False
                    ),
                ),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_registry_states",
                        to="knowledge.knowledgerelease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeActivationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_activation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "activated_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activation_events",
                        to="knowledge.knowledgerelease",
                    ),
                ),
                (
                    "prior_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activation_events_as_prior",
                        to="knowledge.knowledgerelease",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("asset_id", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=500)),
                ("asset_type", models.CharField(max_length=100)),
                ("public_url", models.TextField()),
                ("public_url_sha256", models.CharField(max_length=64)),
                ("short_description", models.CharField(max_length=500)),
                ("detailed_description", models.TextField()),
                ("capability_tags", models.JSONField(default=list)),
                ("ftl_layers", models.JSONField(default=list)),
                ("industries", models.JSONField(default=list)),
                ("languages", models.JSONField(default=list)),
                ("audiences", models.JSONField(default=list)),
                ("confidentiality", models.CharField(max_length=32)),
                ("approved_for_external_use", models.BooleanField(default=False)),
                ("status", models.CharField(max_length=16)),
                ("last_reviewed_at", models.DateTimeField()),
                ("url_last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="knowledge.knowledgerelease",
                    ),
                ),
            ],
            options={
                "ordering": ("asset_id",),
            },
        ),
        migrations.CreateModel(
            name="ApprovedClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("claim_key", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField()),
                ("full_wording", models.TextField()),
                ("short_wording", models.CharField(max_length=500)),
                ("claim_type", models.CharField(max_length=32)),
                ("supporting_asset_ids", models.JSONField(default=list)),
                ("allowed_audiences", models.JSONField(default=list)),
                ("allowed_languages", models.JSONField(default=list)),
                ("paraphrase_allowed", models.BooleanField(default=False)),
                ("strengthening_prohibited", models.BooleanField(default=True)),
                ("valid_from", models.DateField()),
                ("review_due_at", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_claims",
                        to="knowledge.knowledgerelease",
                    ),
                ),
            ],
            options={
                "ordering": ("claim_key",),
            },
        ),
        migrations.CreateModel(
            name="OfferModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=500)),
                ("ftl_layers", models.JSONField(default=list)),
                ("problem_patterns", models.JSONField(default=list)),
                ("description", models.TextField()),
                ("typical_deliverables", models.JSONField(default=list)),
                ("suitable_client_profiles", models.JSONField(default=list)),
                ("infrastructure_options", models.JSONField(default=list)),
                ("exclusions", models.JSONField(default=list)),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="knowledge.knowledgerelease",
                    ),
                ),
            ],
            options={
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="ProhibitedClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("claim_key", models.CharField(max_length=100)),
                ("wording", models.TextField()),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prohibited_claims",
                        to="knowledge.knowledgerelease",
                    ),
                ),
            ],
            options={
                "ordering": ("claim_key",),
            },
        ),
        migrations.AddConstraint(
            model_name="knowledgerelease",
            constraint=models.UniqueConstraint(
                fields=("source_commit", "manifest_sha256"),
                name="knowledge_release_commit_manifest_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("release", "asset_id"), name="knowledge_asset_release_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "confidentiality__in",
                        ("public", "internal", "confidential_client", "embargoed"),
                    )
                ),
                name="knowledge_asset_confidentiality_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("live", "preview", "archived"))),
                name="knowledge_asset_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvedclaim",
            constraint=models.UniqueConstraint(
                fields=("release", "claim_key"), name="knowledge_claim_release_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="offermodule",
            constraint=models.UniqueConstraint(
                fields=("release", "key"), name="knowledge_offer_release_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="prohibitedclaim",
            constraint=models.UniqueConstraint(
                fields=("release", "claim_key"), name="knowledge_prohibited_release_key_unique"
            ),
        ),
    ]
