# Generated by Django 5.2.17 on 2026-08-06 09:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelCapability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("model_id", models.CharField(max_length=128, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("legacy", "Legacy"),
                            ("deprecated", "Deprecated"),
                            ("disabled", "Disabled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("supports_responses", models.BooleanField(default=True)),
                ("supports_structured_outputs", models.BooleanField(default=True)),
                ("supports_web_search", models.BooleanField(default=False)),
                ("web_search_tool_type", models.CharField(blank=True, max_length=64)),
                ("supports_source_list_include", models.BooleanField(default=False)),
                ("supports_background", models.BooleanField(default=False)),
                ("supports_background_store_false", models.BooleanField(default=False)),
                ("supports_reasoning_effort", models.BooleanField(default=True)),
                ("allowed_reasoning_efforts", models.JSONField(default=list)),
                ("supports_store_false", models.BooleanField(default=True)),
                ("maximum_tool_calls", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("effective_from", models.DateField()),
                ("last_smoke_test_at", models.DateTimeField(blank=True, null=True)),
                ("official_reference_snapshot", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("model_id",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["active", "legacy", "deprecated", "disabled"])
                        ),
                        name="providers_capability_status_known",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("policy_key", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=32)),
                ("stage", models.CharField(max_length=100)),
                ("reasoning_effort", models.CharField(default="medium", max_length=16)),
                ("tool_type", models.CharField(blank=True, max_length=64)),
                ("search_context_size", models.CharField(default="medium", max_length=16)),
                ("max_tool_calls", models.PositiveSmallIntegerField(default=8)),
                ("max_output_tokens", models.PositiveIntegerField(default=4000)),
                ("max_cost_usd", models.DecimalField(decimal_places=4, max_digits=8)),
                ("store", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("policy_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="providers.modelcapability",
                    ),
                ),
            ],
            options={
                "ordering": ("policy_key", "-version"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy_key", "version"), name="providers_policy_key_version_unique"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("policy_key",),
                        name="providers_policy_one_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_tool_calls__gte", 1)),
                        name="providers_policy_tool_calls_gte_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_output_tokens__gte", 256)),
                        name="providers_policy_output_gte_256",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_cost_usd__gte", 0)),
                        name="providers_policy_cost_gte_0",
                    ),
                ],
            },
        ),
    ]
