# Generated by Django 5.2.17 on 2026-08-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelpolicy",
            name="max_concurrent_calls",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="modelpolicy",
            name="max_daily_cost_usd",
            field=models.DecimalField(decimal_places=4, default=5, max_digits=10),
        ),
        migrations.AddField(
            model_name="modelpolicy",
            name="max_monthly_cost_usd",
            field=models.DecimalField(decimal_places=4, default=100, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name="modelpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_daily_cost_usd__gte", models.F("max_cost_usd"))),
                name="providers_policy_daily_covers_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_monthly_cost_usd__gte", models.F("max_daily_cost_usd"))),
                name="providers_policy_monthly_covers_daily",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_concurrent_calls__gte", 1)),
                name="providers_policy_concurrency_gte_1",
            ),
        ),
    ]
