# Generated by Django 5.2.17 on 2026-08-06 07:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("operations", "0002_audit_event_immutability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("manual", "Manual"), ("discovery", "Discovery")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("url_original", models.TextField()),
                ("url_canonical", models.TextField(blank=True)),
                ("url_sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                ("source_type_hint", models.CharField(blank=True, max_length=32)),
                ("company_name_hint", models.TextField(blank=True)),
                ("company_domain_hint", models.TextField(blank=True)),
                ("title_hint", models.TextField(blank=True)),
                ("snippet_hint", models.TextField(blank=True)),
                ("matched_terms", models.JSONField(blank=True, default=list)),
                (
                    "candidate_confidence",
                    models.DecimalField(decimal_places=3, max_digits=4, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("fetch_queued", "Fetch queued"),
                            ("registered", "Registered"),
                            ("rejected", "Rejected"),
                            ("unsafe", "Unsafe"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=500)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pipeline_run",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_candidate",
                        to="operations.pipelinerun",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_source_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "permissions": [("submit_public_source", "Can submit a confirmed public source")],
            },
        ),
        migrations.CreateModel(
            name="SourceEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("personio", "Personio"),
                            ("greenhouse", "Greenhouse"),
                            ("lever", "Lever"),
                            ("ashby", "Ashby"),
                            ("json_ld", "JSON-LD"),
                            ("generic_web", "Generic web"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                ("base_url_original", models.TextField()),
                ("base_url_canonical", models.TextField()),
                ("base_url_sha256", models.CharField(max_length=64, unique=True)),
                ("tenant_key", models.CharField(blank=True, max_length=255)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("degraded", "Degraded"),
                            ("blocked", "Blocked"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "robots_policy",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("blocked", "Blocked"),
                            ("unknown", "Unknown"),
                            ("not_applicable", "Not applicable"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("rate_policy_key", models.CharField(default="public_default", max_length=64)),
                ("etag", models.TextField(blank=True)),
                ("last_modified", models.TextField(blank=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("next_allowed_fetch_at", models.DateTimeField(blank=True, null=True)),
                ("connector_key", models.CharField(default="unclassified", max_length=64)),
                ("connector_version", models.CharField(default="1.0.0", max_length=32)),
                ("last_schema_change_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_endpoints",
                        to="sources.sourcecandidate",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_endpoints",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.AddField(
            model_name="sourcecandidate",
            name="registered_endpoint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidate_registrations",
                to="sources.sourceendpoint",
            ),
        ),
        migrations.CreateModel(
            name="SourceArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("storage_key", models.TextField(unique=True)),
                ("sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("content_type", models.CharField(max_length=255)),
                ("encoding", models.CharField(blank=True, max_length=64)),
                ("retrieved_at", models.DateTimeField()),
                (
                    "retention_class",
                    models.CharField(
                        choices=[
                            ("public_source", "Public source"),
                            ("short_lived", "Short lived"),
                            ("legal_hold", "Legal hold"),
                        ],
                        default="public_source",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="sources.sourceendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ("-retrieved_at",),
            },
        ),
        migrations.CreateModel(
            name="FetchAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("requested_url", models.TextField()),
                ("final_url", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("fetched", "Fetched"),
                            ("not_modified", "Not modified"),
                            ("blocked", "Blocked"),
                            ("failed", "Failed"),
                            ("too_large", "Too large"),
                            ("unsupported", "Unsupported"),
                        ],
                        default="started",
                        max_length=16,
                    ),
                ),
                (
                    "network_policy",
                    models.CharField(
                        choices=[("allowed", "Allowed"), ("blocked", "Blocked")],
                        default="allowed",
                        max_length=16,
                    ),
                ),
                (
                    "robots_policy",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("blocked", "Blocked"),
                            ("unknown", "Unknown"),
                            ("not_applicable", "Not applicable"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("elapsed_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("redirect_chain", models.JSONField(blank=True, default=list)),
                ("response_headers_filtered", models.JSONField(blank=True, default=dict)),
                ("body_sha256", models.CharField(blank=True, max_length=64)),
                ("body_size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("encoding", models.CharField(blank=True, max_length=64)),
                ("retryable", models.BooleanField(default=False)),
                ("attempt_count", models.PositiveIntegerField(default=1)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("safe_error_message", models.CharField(blank=True, max_length=500)),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fetch_attempts",
                        to="operations.pipelinerun",
                    ),
                ),
                (
                    "source_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fetch_attempts",
                        to="sources.sourceendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="SourceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("retrieved_at", models.DateTimeField()),
                ("body_sha256", models.CharField(max_length=64)),
                ("content_type", models.CharField(max_length=255)),
                ("encoding", models.CharField(blank=True, max_length=64)),
                ("parser_hint", models.CharField(blank=True, max_length=64)),
                (
                    "retention_class",
                    models.CharField(
                        choices=[
                            ("public_source", "Public source"),
                            ("short_lived", "Short lived"),
                            ("legal_hold", "Legal hold"),
                        ],
                        default="public_source",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="sources.sourceartifact",
                    ),
                ),
                (
                    "fetch_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshot",
                        to="sources.fetchattempt",
                    ),
                ),
                (
                    "source_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="sources.sourceendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ("-retrieved_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="sourceendpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "degraded", "blocked", "archived"])),
                name="sources_endpoint_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("candidate_confidence__isnull", True),
                    models.Q(("candidate_confidence__gte", 0), ("candidate_confidence__lte", 1)),
                    _connector="OR",
                ),
                name="sources_candidate_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["new", "fetch_queued", "registered", "rejected", "unsafe", "duplicate"],
                    )
                ),
                name="sources_candidate_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceartifact",
            constraint=models.UniqueConstraint(
                fields=("source_endpoint", "sha256"), name="sources_artifact_endpoint_sha_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_bytes__gte", 1)), name="sources_artifact_size_gte_1"
            ),
        ),
        migrations.AddIndex(
            model_name="fetchattempt",
            index=models.Index(
                fields=["source_endpoint", "-started_at"], name="sources_attempt_endpoint_time"
            ),
        ),
        migrations.AddIndex(
            model_name="fetchattempt",
            index=models.Index(
                fields=["status", "-started_at"], name="sources_attempt_status_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="fetchattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "started",
                            "fetched",
                            "not_modified",
                            "blocked",
                            "failed",
                            "too_large",
                            "unsupported",
                        ],
                    )
                ),
                name="sources_attempt_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="fetchattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__gte", 1)), name="sources_attempt_count_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="fetchattempt",
            constraint=models.UniqueConstraint(
                fields=("pipeline_run", "attempt_count"), name="sources_attempt_run_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcesnapshot",
            constraint=models.UniqueConstraint(
                fields=("source_endpoint", "body_sha256"),
                name="sources_snapshot_endpoint_sha_unique",
            ),
        ),
    ]
