# Generated by Django 5.2.17 on 2026-08-06 11:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("knowledge", "0001_initial"),
        ("operations", "0002_audit_event_immutability"),
        ("opportunities", "0003_alter_opportunity_research_status"),
        ("research", "0002_immutable_research_evidence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolutionVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("structured_output", models.JSONField(default=dict)),
                ("output_sha256", models.CharField(max_length=64)),
                ("input_sha256", models.CharField(max_length=64)),
                ("prompt_version", models.CharField(default="2.1.0", max_length=32)),
                ("schema_version", models.CharField(default="2.1", max_length=16)),
                ("generator_method", models.CharField(default="deterministic", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_solution_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solution_versions",
                        to="knowledge.offermodule",
                    ),
                ),
                (
                    "knowledge_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solution_versions",
                        to="knowledge.knowledgerelease",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solution_versions",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solution_versions",
                        to="operations.pipelinerun",
                    ),
                ),
                (
                    "research_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solution_versions",
                        to="research.researchrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-version",),
                "permissions": [
                    ("request_solution", "Can request an FTL solution hypothesis"),
                    ("edit_solution", "Can create an edited solution version"),
                    ("approve_solution", "Can approve an exact solution version"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SolutionPhase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("phase_order", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=500)),
                ("objective", models.TextField()),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "solution_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phases",
                        to="solutions.solutionversion",
                    ),
                ),
            ],
            options={
                "ordering": ("phase_order",),
            },
        ),
        migrations.CreateModel(
            name="OpportunitySolutionState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("review_required", "Review required"),
                            ("stale", "Stale"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("stale_reason", models.CharField(blank=True, max_length=500)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_solution_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solution_state",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "approved_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_for_states",
                        to="solutions.solutionversion",
                    ),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_for_states",
                        to="solutions.solutionversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("output_payload", models.JSONField(default=dict)),
                ("output_sha256", models.CharField(max_length=64)),
                ("matcher_version", models.CharField(default="1.0.0", max_length=32)),
                ("candidate_asset_ids", models.JSONField(default=list)),
                ("excluded_reasons", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "knowledge_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_matches",
                        to="knowledge.knowledgerelease",
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_matches",
                        to="operations.pipelinerun",
                    ),
                ),
                (
                    "solution_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_match",
                        to="solutions.solutionversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField()),
                ("supported_solution_phase", models.PositiveSmallIntegerField()),
                ("relevance_reason", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selections",
                        to="knowledge.asset",
                    ),
                ),
                (
                    "asset_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selections",
                        to="solutions.assetmatch",
                    ),
                ),
            ],
            options={
                "ordering": ("priority",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset_match", "asset"), name="solutions_match_asset_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("asset_match", "priority"), name="solutions_match_priority_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("priority__gte", 1), ("priority__lte", 2)),
                        name="solutions_selection_priority_range",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="solutionversion",
            constraint=models.UniqueConstraint(
                fields=("opportunity", "version"), name="solutions_opportunity_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="solutionphase",
            constraint=models.UniqueConstraint(
                fields=("solution_version", "phase_order"),
                name="solutions_phase_version_order_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunitysolutionstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "approved", "review_required", "stale"])
                ),
                name="solutions_state_status_known",
            ),
        ),
    ]
