# Generated by Django 5.2.17 on 2026-08-05 15:24

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pipeline_name", models.CharField(max_length=100)),
                ("stage", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("waiting_external", "Waiting external"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("manual", "Manual"),
                            ("backfill", "Backfill"),
                            ("webhook", "Webhook"),
                            ("recovery", "Recovery"),
                        ],
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("trace_id", models.CharField(blank=True, max_length=128)),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("next_action_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_requested_at", models.DateTimeField(blank=True, null=True)),
                ("input_count", models.PositiveIntegerField(default=0)),
                ("output_count", models.PositiveIntegerField(default=0)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("policy_versions", models.JSONField(blank=True, default=dict)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "actual_cost_usd",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("last_error_message", models.CharField(blank=True, max_length=500)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_pipeline_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("trigger_checkpoint", "Can trigger an operations checkpoint"),
                    ("view_dependency_health", "Can view detailed dependency health"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[("user", "User"), ("system", "System"), ("provider", "Provider")],
                        max_length=16,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("action", models.CharField(max_length=160)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.UUIDField()),
                ("before_summary", models.JSONField(blank=True, default=dict)),
                ("after_summary", models.JSONField(blank=True, default=dict)),
                ("reason_key", models.CharField(blank=True, max_length=100)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("trace_id", models.CharField(blank=True, max_length=128)),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="operations.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at",),
            },
        ),
        migrations.CreateModel(
            name="PipelineStepRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("input_ids", models.JSONField(blank=True, default=dict)),
                ("output_ids", models.JSONField(blank=True, default=dict)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("last_error_message", models.CharField(blank=True, max_length=500)),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="steps",
                        to="operations.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProviderCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("operation", models.CharField(max_length=100)),
                ("request_sha256", models.CharField(max_length=64)),
                ("model_policy_snapshot", models.JSONField(blank=True, default=dict)),
                ("external_response_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("refused", "Refused"),
                            ("incomplete", "Incomplete"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("usage", models.JSONField(blank=True, default=dict)),
                ("tool_calls", models.JSONField(blank=True, default=list)),
                ("cost_metadata", models.JSONField(blank=True, default=dict)),
                ("safe_error_code", models.CharField(blank=True, max_length=64)),
                ("safe_error_message", models.CharField(blank=True, max_length=500)),
                ("retention_class", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_calls",
                        to="operations.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TaskOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("command_type", models.CharField(max_length=160)),
                ("payload", models.JSONField(default=dict)),
                ("payload_schema_version", models.CharField(default="2.1", max_length=16)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("last_error_message", models.CharField(blank=True, max_length=500)),
                ("claimed_by", models.CharField(blank=True, max_length=128)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("broker_message_id", models.CharField(blank=True, max_length=255)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_commands",
                        to="operations.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "permissions": [("retry_taskoutbox", "Can retry an eligible outbox command")],
            },
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(fields=["status", "heartbeat_at"], name="ops_run_status_heartbeat"),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["pipeline_name", "-created_at"], name="ops_run_pipeline_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinerun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["queued", "running", "waiting_external", "complete", "failed", "canceled"],
                    )
                ),
                name="ops_pipeline_status_known",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["object_type", "object_id", "-occurred_at"], name="ops_audit_object_time"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["request_id"], name="ops_audit_request"),
        ),
        migrations.AddIndex(
            model_name="pipelinesteprun",
            index=models.Index(fields=["status", "heartbeat_at"], name="ops_step_status_heartbeat"),
        ),
        migrations.AddIndex(
            model_name="providercall",
            index=models.Index(
                fields=["provider", "operation", "-created_at"], name="ops_provider_operation"
            ),
        ),
        migrations.AddIndex(
            model_name="providercall",
            index=models.Index(fields=["status", "-created_at"], name="ops_provider_status"),
        ),
        migrations.AddIndex(
            model_name="taskoutbox",
            index=models.Index(
                fields=["status", "available_at"], name="ops_outbox_status_available"
            ),
        ),
        migrations.AddIndex(
            model_name="taskoutbox",
            index=models.Index(fields=["claimed_at"], name="ops_outbox_claimed"),
        ),
        migrations.AddConstraint(
            model_name="taskoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "publishing", "published", "failed", "canceled"])
                ),
                name="ops_outbox_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempts__gte", 0)), name="ops_outbox_attempts_gte_0"
            ),
        ),
    ]
