from apps.accounts.models import TeamRoleName

PermissionKey = tuple[str, str]

OPERATIONS_VIEW: tuple[PermissionKey, ...] = (
    ("operations", "view_auditevent"),
    ("operations", "view_pipelinerun"),
    ("operations", "view_pipelinesteprun"),
    ("operations", "view_providercall"),
    ("operations", "view_taskoutbox"),
    ("operations", "view_dependency_health"),
)
SOURCE_VIEW: tuple[PermissionKey, ...] = (
    ("companies", "view_company"),
    ("companies", "view_companydomain"),
    ("companies", "view_companyalias"),
    ("companies", "view_companymergereview"),
    ("sources", "view_sourcecandidate"),
    ("sources", "view_sourceendpoint"),
    ("sources", "view_fetchattempt"),
    ("sources", "view_sourceartifact"),
    ("sources", "view_sourcesnapshot"),
    ("jobs", "view_jobposting"),
    ("jobs", "view_joblocation"),
    ("jobs", "view_jobpostingsnapshot"),
    ("jobs", "view_postingobservation"),
    ("jobs", "view_connectorparseattempt"),
    ("jobs", "view_postingchangeevent"),
    ("jobs", "view_duplicaterelationship"),
    ("jobs", "view_evidencecatalog"),
    ("jobs", "view_evidenceitem"),
    ("discovery", "view_searchdefinition"),
    ("discovery", "view_discoveryrun"),
    ("discovery", "view_discoveryquery"),
    ("discovery", "view_discoverycandidate"),
    ("discovery", "view_endpointwatch"),
    ("providers", "view_modelcapability"),
    ("providers", "view_modelpolicy"),
    ("signals", "view_signalontology"),
    ("signals", "view_signaldetectionattempt"),
    ("signals", "view_signalevent"),
    ("signals", "view_signalevidence"),
    ("signals", "view_signalassessment"),
    ("signals", "view_signalassessmentevidence"),
    ("signals", "view_capabilityclusterrecord"),
    ("signals", "view_capabilitygaprecord"),
    ("signals", "view_assessmentoverride"),
    ("opportunities", "view_opportunity"),
    ("opportunities", "view_companyassessment"),
    ("opportunities", "view_companyfeature"),
    ("opportunities", "view_companypattern"),
    ("opportunities", "view_opportunitysignal"),
    ("opportunities", "view_qualificationoverride"),
    ("research", "view_researchrun"),
    ("research", "view_researchreportartifact"),
    ("research", "view_researchsource"),
    ("research", "view_researchclaim"),
    ("research", "view_researchclaimsource"),
    ("research", "view_researchclaimsignal"),
    ("research", "view_researchclaimevidence"),
    ("research", "view_researchdossier"),
    ("knowledge", "view_knowledgerelease"),
    ("knowledge", "view_knowledgeregistrystate"),
    ("knowledge", "view_offermodule"),
    ("knowledge", "view_approvedclaim"),
    ("knowledge", "view_prohibitedclaim"),
    ("knowledge", "view_asset"),
    ("knowledge", "view_knowledgeactivationevent"),
    ("solutions", "view_solutionversion"),
    ("solutions", "view_opportunitysolutionstate"),
    ("solutions", "view_solutionphase"),
    ("solutions", "view_assetmatch"),
    ("solutions", "view_assetselection"),
    ("contacts", "view_contactresearchrun"),
    ("contacts", "view_buyerroleresult"),
    ("contacts", "view_buyerrolehypothesis"),
    ("contacts", "view_contactsourcetarget"),
    ("contacts", "view_contactsourceartifact"),
    ("contacts", "view_contactevidence"),
    ("contacts", "view_contactperson"),
    ("contacts", "view_contactobservation"),
    ("contacts", "view_contactroute"),
    ("contacts", "view_suppressionentry"),
    ("contacts", "view_contactselection"),
)

ROLE_PERMISSION_CODENAMES: dict[TeamRoleName, tuple[str, ...]] = {
    TeamRoleName.VIEWER: (
        "view_auditevent",
        "view_pipelinerun",
        "view_pipelinesteprun",
        "view_providercall",
        "view_taskoutbox",
        "view_dependency_health",
    ),
    TeamRoleName.RESEARCHER: (
        "view_auditevent",
        "view_pipelinerun",
        "view_pipelinesteprun",
        "view_providercall",
        "view_taskoutbox",
        "view_dependency_health",
        "trigger_checkpoint",
    ),
    TeamRoleName.REVIEWER: (
        "view_auditevent",
        "view_pipelinerun",
        "view_pipelinesteprun",
        "view_providercall",
        "view_taskoutbox",
        "view_dependency_health",
        "trigger_checkpoint",
    ),
    TeamRoleName.FOUNDER: (
        "view_auditevent",
        "view_pipelinerun",
        "view_pipelinesteprun",
        "view_providercall",
        "view_taskoutbox",
        "view_dependency_health",
        "trigger_checkpoint",
        "retry_taskoutbox",
    ),
    TeamRoleName.ADMIN: (
        "view_auditevent",
        "view_pipelinerun",
        "view_pipelinesteprun",
        "view_providercall",
        "view_taskoutbox",
        "view_dependency_health",
        "trigger_checkpoint",
        "retry_taskoutbox",
    ),
}

ROLE_PERMISSION_KEYS: dict[TeamRoleName, tuple[PermissionKey, ...]] = {
    TeamRoleName.VIEWER: OPERATIONS_VIEW + SOURCE_VIEW,
    TeamRoleName.RESEARCHER: OPERATIONS_VIEW
    + SOURCE_VIEW
    + (
        ("operations", "trigger_checkpoint"),
        ("sources", "submit_public_source"),
        ("discovery", "run_searchdefinition"),
        ("research", "request_research"),
        ("solutions", "request_solution"),
        ("solutions", "edit_solution"),
        ("contacts", "request_contact_research"),
    ),
    TeamRoleName.REVIEWER: OPERATIONS_VIEW
    + SOURCE_VIEW
    + (
        ("operations", "trigger_checkpoint"),
        ("signals", "review_signalevent"),
        ("signals", "override_signalassessment"),
        ("opportunities", "override_opportunity"),
        ("research", "request_research"),
        ("solutions", "edit_solution"),
        ("solutions", "approve_solution"),
        ("contacts", "request_contact_research"),
        ("contacts", "add_human_route"),
        ("contacts", "review_contact_route"),
        ("contacts", "select_contact_route"),
        ("contacts", "add_suppression"),
    ),
    TeamRoleName.FOUNDER: OPERATIONS_VIEW
    + SOURCE_VIEW
    + (
        ("operations", "trigger_checkpoint"),
        ("operations", "retry_taskoutbox"),
        ("sources", "submit_public_source"),
        ("jobs", "reparse_source_snapshot"),
        ("discovery", "run_searchdefinition"),
        ("signals", "review_signalevent"),
        ("signals", "override_signalassessment"),
        ("opportunities", "override_opportunity"),
        ("research", "request_research"),
        ("knowledge", "sync_knowledge"),
        ("knowledge", "activate_knowledge"),
        ("solutions", "request_solution"),
        ("solutions", "edit_solution"),
        ("solutions", "approve_solution"),
        ("contacts", "request_contact_research"),
        ("contacts", "add_human_route"),
        ("contacts", "review_contact_route"),
        ("contacts", "select_contact_route"),
        ("contacts", "add_suppression"),
    ),
    TeamRoleName.ADMIN: OPERATIONS_VIEW
    + SOURCE_VIEW
    + (
        ("operations", "trigger_checkpoint"),
        ("operations", "retry_taskoutbox"),
        ("sources", "submit_public_source"),
        ("jobs", "reparse_source_snapshot"),
        ("discovery", "run_searchdefinition"),
        ("discovery", "version_searchdefinition"),
        ("signals", "review_signalevent"),
        ("signals", "override_signalassessment"),
        ("opportunities", "override_opportunity"),
        ("research", "request_research"),
        ("knowledge", "sync_knowledge"),
        ("knowledge", "activate_knowledge"),
        ("solutions", "request_solution"),
        ("solutions", "edit_solution"),
        ("solutions", "approve_solution"),
        ("contacts", "request_contact_research"),
        ("contacts", "add_human_route"),
        ("contacts", "review_contact_route"),
        ("contacts", "select_contact_route"),
        ("contacts", "add_suppression"),
    ),
}
