# Generated by Django 5.2.17 on 2026-08-06 10:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0002_companymergereview_companies_one_open_merge_review_pair"),
        ("jobs", "0006_evidencecatalog_evidenceitem_and_more"),
        ("operations", "0002_audit_event_immutability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalOntology",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.CharField(max_length=32, unique=True)),
                ("allowed_signal_types", models.JSONField(default=list)),
                ("allowed_capability_tags", models.JSONField(default=list)),
                ("rule_payload", models.JSONField(default=dict)),
                ("ontology_sha256", models.CharField(max_length=64, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SignalDetectionAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("no_signal", "No signal"),
                            ("failed", "Failed"),
                            ("review_required", "Review required"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                (
                    "detector_method",
                    models.CharField(
                        choices=[
                            ("deterministic", "Deterministic"),
                            ("model_assisted", "Model assisted"),
                        ],
                        default="deterministic",
                        max_length=24,
                    ),
                ),
                ("prompt_version", models.CharField(max_length=32)),
                ("schema_version", models.CharField(max_length=32)),
                ("detector_version", models.CharField(max_length=32)),
                ("input_sha256", models.CharField(blank=True, max_length=64)),
                ("output_payload", models.JSONField(blank=True, default=dict)),
                ("no_signal_reason", models.CharField(blank=True, max_length=500)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("safe_error_message", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signal_detection_attempts",
                        to="jobs.postingchangeevent",
                    ),
                ),
                (
                    "evidence_catalog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signal_detection_attempts",
                        to="jobs.evidencecatalog",
                    ),
                ),
                (
                    "pipeline_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signal_detection_attempt",
                        to="operations.pipelinerun",
                    ),
                ),
                (
                    "provider_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signal_detection_attempts",
                        to="operations.providercall",
                    ),
                ),
                (
                    "ontology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detection_attempts",
                        to="signals.signalontology",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SignalEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("capability_hiring", "Capability hiring"),
                            ("material_description_change", "Material description change"),
                            ("role_reposted", "Role reposted"),
                            ("role_reopened", "Role reopened"),
                            ("role_closed", "Role closed"),
                        ],
                        max_length=48,
                    ),
                ),
                ("event_kind", models.CharField(max_length=16)),
                ("capability_tags", models.JSONField(default=list)),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("rationale", models.CharField(max_length=1000)),
                ("occurred_at", models.DateTimeField()),
                ("observed_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("retracted", "Retracted")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("confirmed", "Confirmed"),
                            ("false_positive", "False positive"),
                        ],
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_reason", models.CharField(blank=True, max_length=500)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("ontology_version", models.CharField(max_length=32)),
                ("prompt_version", models.CharField(max_length=32)),
                ("schema_version", models.CharField(max_length=32)),
                ("detector_version", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signals",
                        to="jobs.postingchangeevent",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signal_events",
                        to="companies.company",
                    ),
                ),
                (
                    "detection_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signals",
                        to="signals.signaldetectionattempt",
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signal_events",
                        to="jobs.jobposting",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_signal_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-observed_at", "-created_at"),
                "permissions": [("review_signalevent", "Can review and retract a signal event")],
            },
        ),
        migrations.CreateModel(
            name="SignalEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evidence_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signal_links",
                        to="jobs.evidenceitem",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_links",
                        to="signals.signalevent",
                    ),
                ),
            ],
            options={
                "ordering": ("evidence_item__public_id",),
            },
        ),
        migrations.AddConstraint(
            model_name="signalevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "signal_type__in",
                        [
                            "capability_hiring",
                            "material_description_change",
                            "role_reposted",
                            "role_reopened",
                            "role_closed",
                        ],
                    )
                ),
                name="signals_event_type_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="signalevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "retracted"])),
                name="signals_event_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="signalevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="signals_event_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="signalevidence",
            constraint=models.UniqueConstraint(
                fields=("signal", "evidence_item"), name="signals_evidence_signal_item_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="signaldetectionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["queued", "running", "complete", "no_signal", "failed", "review_required"],
                    )
                ),
                name="signals_attempt_status_known",
            ),
        ),
    ]
