# Generated by Django 5.2.17 on 2026-08-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signals", "0002_signal_evidence_immutability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signalevent",
            name="review_state",
            field=models.CharField(
                choices=[
                    ("unreviewed", "Unreviewed"),
                    ("confirmed", "Confirmed"),
                    ("false_positive", "False positive"),
                    ("superseded", "Superseded by detector policy"),
                ],
                default="unreviewed",
                max_length=24,
            ),
        ),
    ]
