# Generated by Django 5.2.17 on 2026-08-06 10:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_evidence_immutability"),
        ("operations", "0002_audit_event_immutability"),
        ("signals", "0003_alter_signalevent_review_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("review_required", "Review required"),
                            ("failed", "Failed"),
                            ("superseded", "Superseded"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("classification_method", models.CharField(default="deterministic", max_length=24)),
                ("ontology_version", models.CharField(max_length=32)),
                ("scoring_policy_version", models.CharField(max_length=32)),
                (
                    "prompt_key",
                    models.CharField(default="capability_gap_classifier", max_length=64),
                ),
                ("prompt_version", models.CharField(max_length=32)),
                ("schema_version", models.CharField(max_length=32)),
                ("structured_output", models.JSONField(blank=True, default=dict)),
                ("component_values", models.JSONField(blank=True, default=dict)),
                ("component_coverage", models.JSONField(blank=True, default=dict)),
                ("missing_components", models.JSONField(blank=True, default=list)),
                ("capability_relevance", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("score_coverage", models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                (
                    "opportunity_mode",
                    models.CharField(
                        choices=[
                            ("employment_only", "Employment only"),
                            ("external_service", "External service"),
                            ("hybrid", "Hybrid"),
                            ("watch_signal", "Watch signal"),
                            ("irrelevant", "Irrelevant"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=24,
                    ),
                ),
                ("mode_confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("mode_rationale", models.CharField(max_length=1000)),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("input_sha256", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("safe_error_message", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pipeline_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signal_assessment",
                        to="operations.pipelinerun",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="signals.signalevent",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CapabilityGapRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("gap_key", models.CharField(max_length=100)),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("rationale", models.CharField(max_length=1000)),
                ("evidence_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capability_gaps",
                        to="signals.signalassessment",
                    ),
                ),
            ],
            options={
                "ordering": ("gap_key",),
            },
        ),
        migrations.CreateModel(
            name="CapabilityClusterRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cluster_key", models.CharField(max_length=100)),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("evidence_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capability_clusters",
                        to="signals.signalassessment",
                    ),
                ),
            ],
            options={
                "ordering": ("cluster_key",),
            },
        ),
        migrations.CreateModel(
            name="AssessmentOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "opportunity_mode",
                    models.CharField(
                        choices=[
                            ("employment_only", "Employment only"),
                            ("external_service", "External service"),
                            ("hybrid", "Hybrid"),
                            ("watch_signal", "Watch signal"),
                            ("irrelevant", "Irrelevant"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signal_assessment_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overrides",
                        to="signals.signalassessment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "permissions": [("override_signalassessment", "Can override a signal assessment")],
            },
        ),
        migrations.CreateModel(
            name="SignalAssessmentEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(default="classification_input", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_links",
                        to="signals.signalassessment",
                    ),
                ),
                (
                    "evidence_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_links",
                        to="jobs.evidenceitem",
                    ),
                ),
            ],
            options={
                "ordering": ("evidence_item__public_id",),
            },
        ),
        migrations.AddConstraint(
            model_name="signalassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "queued",
                            "running",
                            "completed",
                            "review_required",
                            "failed",
                            "superseded",
                        ],
                    )
                ),
                name="signals_assessment_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="signalassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "opportunity_mode__in",
                        [
                            "employment_only",
                            "external_service",
                            "hybrid",
                            "watch_signal",
                            "irrelevant",
                            "unknown",
                        ],
                    )
                ),
                name="signals_assessment_mode_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="signalassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capability_relevance__isnull", True),
                    ("capability_relevance__lte", 100),
                    _connector="OR",
                ),
                name="signals_assessment_relevance_lte_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="signalassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode_confidence__gte", 0), ("mode_confidence__lte", 1)),
                name="signals_assessment_mode_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilitygaprecord",
            constraint=models.UniqueConstraint(
                fields=("assessment", "gap_key"), name="signals_gap_assessment_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilityclusterrecord",
            constraint=models.UniqueConstraint(
                fields=("assessment", "cluster_key"), name="signals_cluster_assessment_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="signalassessmentevidence",
            constraint=models.UniqueConstraint(
                fields=("assessment", "evidence_item"), name="signals_assessment_evidence_unique"
            ),
        ),
    ]
