# Generated by Django 5.2.17 on 2026-08-06 11:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0007_evidence_immutability"),
        ("operations", "0002_audit_event_immutability"),
        ("opportunities", "0003_alter_opportunity_research_status"),
        ("signals", "0005_assessment_evidence_immutability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_id", models.CharField(max_length=16)),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("observed_fact", "Observed fact"),
                            ("inference", "Inference"),
                            ("hypothesis", "Hypothesis"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "claim_category",
                    models.CharField(
                        choices=[
                            ("company_profile", "Company profile"),
                            ("signal_context", "Signal context"),
                            ("organizational_ownership", "Organizational ownership"),
                            ("external_partner_context", "External partner context"),
                            (
                                "infrastructure_privacy_governance",
                                "Infrastructure, privacy, and governance",
                            ),
                            ("evidence_against", "Evidence against"),
                            ("other", "Other"),
                        ],
                        max_length=48,
                    ),
                ),
                ("statement", models.CharField(max_length=2000)),
                ("source_ids", models.JSONField(default=list)),
                ("signal_ids", models.JSONField(default=list)),
                ("evidence_ids", models.JSONField(default=list)),
                ("confidence", models.DecimalField(decimal_places=3, max_digits=4)),
                ("current_as_of", models.DateField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("conflict_group", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("public_id",),
            },
        ),
        migrations.CreateModel(
            name="ResearchClaimEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.researchclaim"
                    ),
                ),
                (
                    "evidence_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="jobs.evidenceitem"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="researchclaim",
            name="evidence_items",
            field=models.ManyToManyField(
                through="research.ResearchClaimEvidence", to="jobs.evidenceitem"
            ),
        ),
        migrations.CreateModel(
            name="ResearchClaimSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.researchclaim"
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="signals.signalevent"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="researchclaim",
            name="signals",
            field=models.ManyToManyField(
                through="research.ResearchClaimSignal", to="signals.signalevent"
            ),
        ),
        migrations.CreateModel(
            name="ResearchRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("in_progress", "In progress"),
                            ("source_complete", "Source complete"),
                            ("registering_sources", "Registering sources"),
                            ("extracting", "Extracting"),
                            ("complete", "Complete"),
                            ("partial", "Partial"),
                            ("review_required", "Review required"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("stale", "Stale"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("brief_payload", models.JSONField(default=dict)),
                ("brief_sha256", models.CharField(max_length=64)),
                ("public_input_payload", models.JSONField(default=dict)),
                ("public_input_sha256", models.CharField(max_length=64)),
                ("source_registry_sha256", models.CharField(blank=True, max_length=64)),
                ("extraction_output", models.JSONField(blank=True, default=dict)),
                ("research_prompt_version", models.CharField(default="2.1.0", max_length=32)),
                ("extraction_prompt_version", models.CharField(default="2.1.0", max_length=32)),
                ("schema_version", models.CharField(default="2.1", max_length=32)),
                ("public_policy_key", models.CharField(max_length=100)),
                ("public_policy_version", models.CharField(max_length=32)),
                ("extraction_policy_key", models.CharField(max_length=100)),
                ("extraction_policy_version", models.CharField(max_length=32)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("safe_error_message", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("source_completed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extraction_provider_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extracted_research_runs",
                        to="operations.providercall",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_runs",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "pipeline_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standard_research_run",
                        to="operations.pipelinerun",
                    ),
                ),
                (
                    "public_provider_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="public_research_runs",
                        to="operations.providercall",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_research_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-version", "-created_at"),
                "permissions": [("request_research", "Can request standard company research")],
            },
        ),
        migrations.CreateModel(
            name="ResearchReportArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("storage_key", models.CharField(max_length=1000, unique=True)),
                ("sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("content_type", models.CharField(default="text/markdown", max_length=100)),
                ("renderer_hint", models.CharField(default="plain_markdown", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "research_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_artifact",
                        to="research.researchrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchDossier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("markdown_text", models.TextField()),
                ("markdown_sha256", models.CharField(max_length=64)),
                ("renderer_version", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "research_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dossier",
                        to="research.researchrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="researchclaim",
            name="research_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims",
                to="research.researchrun",
            ),
        ),
        migrations.CreateModel(
            name="ResearchSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_id", models.CharField(max_length=16)),
                ("exact_provider_url", models.TextField()),
                ("canonical_url", models.TextField()),
                ("canonical_url_sha256", models.CharField(max_length=64)),
                ("title", models.CharField(blank=True, max_length=1000)),
                ("publisher", models.CharField(blank=True, max_length=500)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("official_company", "Official company"),
                            ("official_registry", "Official registry"),
                            ("official_government", "Official government"),
                            ("reputable_press", "Reputable press"),
                            ("public_other", "Other public source"),
                        ],
                        max_length=32,
                    ),
                ),
                ("retrieved_at", models.DateTimeField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("provider_reference", models.JSONField(blank=True, default=dict)),
                ("citation_locations", models.JSONField(blank=True, default=list)),
                ("content_sha256", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "research_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="research.researchrun",
                    ),
                ),
            ],
            options={
                "ordering": ("public_id",),
            },
        ),
        migrations.CreateModel(
            name="ResearchClaimSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.researchclaim"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.researchsource"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="researchclaim",
            name="sources",
            field=models.ManyToManyField(
                through="research.ResearchClaimSource", to="research.researchsource"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchclaimevidence",
            constraint=models.UniqueConstraint(
                fields=("claim", "evidence_item"), name="research_claim_evidence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchclaimsignal",
            constraint=models.UniqueConstraint(
                fields=("claim", "signal"), name="research_claim_signal_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchrun",
            constraint=models.UniqueConstraint(
                fields=("opportunity", "version"), name="research_run_opportunity_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("opportunity",),
                name="research_one_current_run_per_opportunity",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "draft",
                            "queued",
                            "in_progress",
                            "source_complete",
                            "registering_sources",
                            "extracting",
                            "complete",
                            "partial",
                            "review_required",
                            "failed",
                            "canceled",
                            "stale",
                        ],
                    )
                ),
                name="research_run_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchsource",
            constraint=models.UniqueConstraint(
                fields=("research_run", "public_id"), name="research_source_run_public_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchsource",
            constraint=models.UniqueConstraint(
                fields=("research_run", "canonical_url_sha256"),
                name="research_source_run_url_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source_type__in",
                        [
                            "official_company",
                            "official_registry",
                            "official_government",
                            "reputable_press",
                            "public_other",
                        ],
                    )
                ),
                name="research_source_type_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchclaimsource",
            constraint=models.UniqueConstraint(
                fields=("claim", "source"), name="research_claim_source_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchclaim",
            constraint=models.UniqueConstraint(
                fields=("research_run", "public_id"), name="research_claim_run_public_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("claim_type__in", ["observed_fact", "inference", "hypothesis", "unknown"])
                ),
                name="research_claim_type_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "claim_category__in",
                        [
                            "company_profile",
                            "signal_context",
                            "organizational_ownership",
                            "external_partner_context",
                            "infrastructure_privacy_governance",
                            "evidence_against",
                            "other",
                        ],
                    )
                ),
                name="research_claim_category_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="research_claim_confidence_range",
            ),
        ),
    ]
