# Generated by Django 5.2.17 on 2026-08-06 09:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("operations", "0002_audit_event_immutability"),
        ("sources", "0002_immutable_source_records"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("logical_window_start", models.DateTimeField()),
                ("logical_window_end", models.DateTimeField()),
                (
                    "run_reason",
                    models.CharField(
                        choices=[("scheduled", "Scheduled"), ("manual", "Manual")], max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("max_tool_calls", models.PositiveSmallIntegerField(default=8)),
                ("max_candidates", models.PositiveSmallIntegerField(default=50)),
                ("max_provider_cost_usd", models.DecimalField(decimal_places=4, max_digits=8)),
                ("known_endpoints_queued", models.PositiveIntegerField(default=0)),
                ("candidates_found", models.PositiveIntegerField(default=0)),
                ("accepted_candidates", models.PositiveIntegerField(default=0)),
                ("unsafe_candidates", models.PositiveIntegerField(default=0)),
                ("duplicate_candidates", models.PositiveIntegerField(default=0)),
                ("first_party_candidates", models.PositiveIntegerField(default=0)),
                (
                    "provider_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("warnings", models.JSONField(default=list)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("safe_error_message", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pipeline_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discovery_run",
                        to="operations.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ("-logical_window_end", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="DiscoveryQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ordinal", models.PositiveSmallIntegerField()),
                ("query_text", models.TextField()),
                ("query_sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=16,
                    ),
                ),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("safe_error_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_call",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discovery_query",
                        to="operations.providercall",
                    ),
                ),
                (
                    "discovery_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queries",
                        to="discovery.discoveryrun",
                    ),
                ),
            ],
            options={
                "ordering": ("ordinal",),
            },
        ),
        migrations.CreateModel(
            name="DiscoveryCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url_sha256", models.CharField(max_length=64)),
                ("provider_source_reference", models.CharField(blank=True, max_length=500)),
                ("location_hints", models.JSONField(default=list)),
                ("first_party", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discovery_provenance",
                        to="sources.sourcecandidate",
                    ),
                ),
                (
                    "discovery_query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discovery_candidates",
                        to="discovery.discoveryquery",
                    ),
                ),
                (
                    "discovery_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discovery_candidates",
                        to="discovery.discoveryrun",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="EndpointWatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("poll_interval_hours", models.PositiveSmallIntegerField(default=24)),
                ("next_poll_at", models.DateTimeField()),
                ("last_queued_at", models.DateTimeField(blank=True, null=True)),
                ("lease_owner", models.CharField(blank=True, max_length=128)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_endpoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discovery_watch",
                        to="sources.sourceendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ("next_poll_at",),
            },
        ),
        migrations.CreateModel(
            name="SearchDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("definition_key", models.SlugField(max_length=100)),
                ("version", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("query_template", models.TextField()),
                ("language", models.CharField(default="en", max_length=16)),
                ("countries", models.JSONField(default=list)),
                ("locations", models.JSONField(default=list)),
                ("capability_clusters", models.JSONField(default=list)),
                ("positive_terms", models.JSONField(default=list)),
                ("negative_terms", models.JSONField(default=list)),
                ("preferred_domains", models.JSONField(default=list)),
                ("excluded_domains", models.JSONField(default=list)),
                ("source_type_filters", models.JSONField(default=list)),
                ("schedule_key", models.CharField(default="daily_morning", max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("max_candidates", models.PositiveSmallIntegerField(default=50)),
                ("lookback_days", models.PositiveSmallIntegerField(default=21)),
                ("payload_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_search_definitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("definition_key", "-version"),
                "permissions": [
                    ("run_searchdefinition", "Can run a search definition"),
                    ("version_searchdefinition", "Can create a search definition version"),
                ],
            },
        ),
        migrations.AddField(
            model_name="discoveryrun",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="discovery.searchdefinition",
            ),
        ),
        migrations.AddConstraint(
            model_name="discoveryquery",
            constraint=models.UniqueConstraint(
                fields=("discovery_run", "ordinal"), name="discovery_query_run_ordinal_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="discoveryquery",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["queued", "complete", "failed", "skipped"])),
                name="discovery_query_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="discoverycandidate",
            constraint=models.UniqueConstraint(
                fields=("discovery_run", "url_sha256"), name="discovery_candidate_run_url_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="endpointwatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("poll_interval_hours__gte", 1)),
                name="discovery_watch_interval_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchdefinition",
            constraint=models.UniqueConstraint(
                fields=("definition_key", "version"), name="discovery_definition_key_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="searchdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("definition_key",),
                name="discovery_definition_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="discovery_definition_version_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="searchdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_candidates__gte", 1), ("max_candidates__lte", 200)),
                name="discovery_definition_candidates_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="discoveryrun",
            constraint=models.UniqueConstraint(
                fields=("definition", "logical_window_start", "logical_window_end", "run_reason"),
                name="discovery_run_definition_window_reason_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="discoveryrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("logical_window_end__gt", models.F("logical_window_start"))),
                name="discovery_run_window_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="discoveryrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["queued", "running", "complete", "partial", "failed", "canceled"],
                    )
                ),
                name="discovery_run_status_known",
            ),
        ),
    ]
