# Generated by Django 5.2.17 on 2026-08-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0001_initial"),
        ("operations", "0002_audit_event_immutability"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveryrun",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discoveryrun",
            name="lease_owner",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name="discoveryrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lease_owner", ""), ("lease_expires_at__isnull", False), _connector="OR"
                ),
                name="discovery_run_lease_owner_expiry",
            ),
        ),
    ]
